/*
 * TestFrame.java
 * Created on Dec 23, 2009, 12:05:29 PM
 *
 * Volume Viewer - Display and manipulate 3D volumetric data
 * Copyright © 2009, Mark McKay
 * http://www.kitfox.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.kitfox.volume.test;

import com.kitfox.volume.light.LightCtrlPanel;
import com.kitfox.volume.transfer.TransferFnPanel;
import com.kitfox.volume.viewer.DataSamplerImage;
import com.kitfox.volume.viewer.ViewerCube;
import com.kitfox.volume.viewer.ViewerPanel;
import com.kitfox.volume.viewer.VolumeData;
import com.kitfox.volume.viewer.VolumeLayoutPanel;
import com.kitfox.volume.viewer.ZipDataLoader;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JPopupMenu;

/**
 *
 * @author kitfox
 */
public class TestFrame extends javax.swing.JFrame
{
    private static final long serialVersionUID = 0;

    JDialog dlgXferPanel = new JDialog();
    JDialog dlgLightPanel = new JDialog();
    JDialog dlgLayoutPanel = new JDialog();

    TransferFnPanel xferPanel = new TransferFnPanel();

    ViewerPanel viewer = new ViewerPanel();
    LightCtrlPanel lightPanel = new LightCtrlPanel();
    VolumeLayoutPanel layoutPanel = new VolumeLayoutPanel();

    ViewerCube cube = new ViewerCube();

    /** Creates new form TestFrame */
    public TestFrame()
    {
        initComponents();

        getContentPane().add(viewer, BorderLayout.CENTER);
//        panel_viewer.add(viewer, BorderLayout.CENTER);
//        panel_light.add(lightPanel, BorderLayout.CENTER);

        viewer.setCube(cube);
        lightPanel.setCube(cube);
        layoutPanel.setCube(cube);
        
        try {
//            VolumeTexture tex = ZipDataLoader.createSampler(TestFrame.class.getResource("/mrbrain-8bit.zip"));
//            cube.setTexture(tex);
            DataSamplerImage tex = ZipDataLoader.createSampler(TestFrame.class.getResource("/mrbrain-8bit.zip"));
            System.err.println("Loaded images");
            VolumeData data =
                    new VolumeData(tex.getxSpan(), tex.getySpan(), tex.getzSpan(), tex);
            System.err.println("Sampled data");
            cube.setData(data);

            xferPanel.setVolumeData(data);
        } catch (IOException ex) {
            Logger.getLogger(TestFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        buildWindows();

        setSize(640, 480);
    }

    private void buildWindows()
    {
        dlgXferPanel.add(xferPanel, BorderLayout.CENTER);
        dlgXferPanel.pack();
        dlgXferPanel.setLocation(640, 0);
        dlgXferPanel.setTitle("Transfer Function / Histogram");
        dlgXferPanel.setVisible(true);

        dlgLightPanel.add(lightPanel, BorderLayout.CENTER);
        dlgLightPanel.pack();
        dlgLightPanel.setLocation(640, 480);
        dlgLightPanel.setTitle("Light");
        dlgLightPanel.setVisible(true);

        dlgLayoutPanel.add(layoutPanel, BorderLayout.CENTER);
        dlgLayoutPanel.pack();
        dlgLayoutPanel.setLocation(0, 480);
        dlgLayoutPanel.setTitle("Layout");
        dlgLayoutPanel.setVisible(true);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_window = new javax.swing.JMenu();
        cm_winXferFn = new javax.swing.JMenuItem();
        cm_winLighting = new javax.swing.JMenuItem();
        cm_winLayout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_window.setText("Window");

        cm_winXferFn.setText("Transfer Function");
        cm_winXferFn.setToolTipText("Paint colors onto the rendered volume");
        cm_winXferFn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm_winXferFnActionPerformed(evt);
            }
        });
        menu_window.add(cm_winXferFn);

        cm_winLighting.setText("Lighting");
        cm_winLighting.setToolTipText("Adjust lighting values");
        cm_winLighting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm_winLightingActionPerformed(evt);
            }
        });
        menu_window.add(cm_winLighting);

        cm_winLayout.setText("Layout");
        cm_winLayout.setToolTipText("Adjust the rendered shape");
        cm_winLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm_winLayoutActionPerformed(evt);
            }
        });
        menu_window.add(cm_winLayout);

        jMenuBar1.add(menu_window);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cm_winXferFnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm_winXferFnActionPerformed
        dlgXferPanel.setVisible(true);
    }//GEN-LAST:event_cm_winXferFnActionPerformed

    private void cm_winLightingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm_winLightingActionPerformed
        dlgLightPanel.setVisible(true);
    }//GEN-LAST:event_cm_winLightingActionPerformed

    private void cm_winLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm_winLayoutActionPerformed
        dlgLayoutPanel.setVisible(true);
    }//GEN-LAST:event_cm_winLayoutActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        JPopupMenu.setDefaultLightWeightPopupEnabled(false);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cm_winLayout;
    private javax.swing.JMenuItem cm_winLighting;
    private javax.swing.JMenuItem cm_winXferFn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_window;
    // End of variables declaration//GEN-END:variables

}
